####################################################
# FRITZ!View Layout
####################################################

LCD4LINUX_BINARY=/mod/sbin/lcd4linux

LCD4LINUX_CONF=/mod/etc/lcd4linux.conf

LCD4LINUX_PLUGIN=fritzview

SHOW_SECONDS=yes

SHOW_HOSTS=yes

SHOW_WLAN=yes

############################################################
# Anzeige
############################################################

DISPLAY_DRIVER=console

LCD_WIDTH=320
LCD_HEIGHT=240

FONT=6x8

ROTATE=0

DISPLAY=DPF

############################################################
# Zeiten
############################################################

UPDATE_INTERVAL=10
PAGE_TIMEOUT=5

############################################################
# Theme
############################################################

THEME=avm

############################################################
# Bootscreen
############################################################

BOOT_THEME=avm
