#!/bin/bash

LCDCFG="/tmp/lcd4linux.conf"

############################################################
# Start
############################################################

lcd_begin()
{
cat >"$LCDCFG" <<EOF
# generated by FRITZ!View

Display '$LCD_NAME'

EOF
}

############################################################
# LCD4Linux Driver
############################################################

display_driver_init()
{
    mkdir -p /tmp/fritzview
    : >/tmp/fritzview/screen.txt

    lcd_config_generate

    if ! pgrep -x lcd4linux >/dev/null
    then
        echo "Starte lcd4linux..."
        lcd4linux -F -q -f "$LCDCFG" >/tmp/lcd4linux.log 2>&1 &
        sleep 1
    fi
}

display_driver_render()
{
    [ -n "$1" ] && printf "%b" "$1" >/tmp/fritzview/screen.txt

    lcd_refresh
}

lcd_refresh()
{
    #if pidof lcd4linux >/dev/null
    #then
     #   kill -HUP "$(pidof lcd4linux)"
    #else
     #   lcd4linux -f "$LCDCFG" &
      #  sleep 1
    #fi
    
    :
    
}

############################################################
# Variables
############################################################

lcd_add_variables()
{
cat >>"$LCDCFG" <<EOF

Variables {

    tick    1000
    tack     500
    minute 60000

}

EOF
}

############################################################
# Display
############################################################

lcd_add_display_dpf()
{
cat >>"$LCDCFG" <<EOF

Display $LCD_NAME {

    Driver '$LCD_DRIVER'

    Port '$LCD_PORT'

    Font '$LCD_FONT'

    Foreground '$LCD_FOREGROUND'
    Background '$LCD_BACKGROUND'
    Basecolor '$LCD_BASECOLOR'

}

EOF
}

############################################################
# Text Widget
############################################################

lcd_add_widget_screen()
{
for ROW in $(seq 1 20)
do
cat >>"$LCDCFG" <<EOF

Widget Line$(printf "%02d" "$ROW") {

    class 'Text'

    expression file::readline('/tmp/fritzview/screen.txt',$ROW)

    width 40

    align 'L'

    update tick

}

EOF
done
}

############################################################
# Layout
############################################################

lcd_add_layout_default()
{
cat >>"$LCDCFG" <<EOF

Layout $LCD_LAYOUT {

EOF

for ROW in $(seq 1 20)
do
cat >>"$LCDCFG" <<EOF
    Row$ROW {

        Col1 'Line$(printf "%02d" "$ROW")'

    }

EOF
done

cat >>"$LCDCFG" <<EOF
}

Layout '$LCD_LAYOUT'

EOF
}

############################################################
# Finish
############################################################

lcd_finish()
{
    :
}

############################################################
# Generator
############################################################

lcd_config_generate()
{
    lcd_begin

    lcd_add_variables

    lcd_add_display_dpf

    lcd_add_widget_screen

    lcd_add_layout_default

    lcd_finish
    
    chmod 600 "$LCDCFG"
    
}

############################################################
# Debug
############################################################

lcd_show_config()
{
    cat "$LCDCFG"
}
