#!/bin/sh

LCDCFG="/tmp/lcd4linux.conf"

############################################################
# Start
############################################################

lcd_begin()
{
cat >"$LCDCFG" <<EOF
# generated by FRITZ!View

Display '$LCD_NAME'

EOF
}

############################################################
# LCD4Linux Driver
############################################################

display_driver_init()
{
    mkdir -p /tmp/fritzview

    : >/tmp/fritzview/screen.txt

    lcd_config_generate
}

display_driver_render()
{
    printf "%b" "$1" >/tmp/fritzview/screen.txt

    lcd_refresh
}

lcd_refresh()
{
    if pidof lcd4linux >/dev/null
    then
        killall -HUP lcd4linux
    else
        lcd4linux -F -f "$LCDCFG" &
    fi
}

############################################################
# Variables
############################################################

lcd_add_variables()
{
cat >>"$LCDCFG" <<EOF

Variables {

    tick    1000
    tack     500
    minute 60000

}

EOF
}

############################################################
# Display
############################################################

lcd_add_display_dpf()
{
cat >>"$LCDCFG" <<EOF

Display $LCD_NAME {

    Driver '$LCD_DRIVER'

    Port '$LCD_PORT'

    Font '$LCD_FONT'

    Foreground '$LCD_FOREGROUND'
    Background '$LCD_BACKGROUND'
    Basecolor '$LCD_BASECOLOR'

}

EOF
}

############################################################
# Text Widget
############################################################

lcd_add_widget_screen()
{
cat >>"$LCDCFG" <<EOF

Widget Screen {

    class 'Text'

    expression 'Hallo FRITZ!View!'

    width 40

    align 'L'

    update tick

}

EOF
}

############################################################
# Layout
############################################################

lcd_add_layout_default()
{
cat >>"$LCDCFG" <<EOF

Layout $LCD_LAYOUT {

    Row1 {

        Col1 'Screen'

    }

}

Layout '$LCD_LAYOUT'

EOF
}

############################################################
# Finish
############################################################

lcd_finish()
{
    :
}

############################################################
# Generator
############################################################

lcd_config_generate()
{
    lcd_begin

    lcd_add_variables

    lcd_add_display_dpf

    lcd_add_widget_screen

    lcd_add_layout_default

    lcd_finish
    
    chmod 600 "$LCDCFG"
    
}

############################################################
# Debug
############################################################

lcd_show_config()
{
    cat "$LCDCFG"
}
